# Generated by Django 5.1.2 on 2024-10-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshowcase', '0002_composition_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='genre',
            field=models.CharField(choices=[('classical', 'Classical'), ('acoustic', 'Acoustic'), ('rock', 'Rock'), ('pop', 'Pop'), ('hip_hop', 'Hip Hop'), ('electronic', 'Electronic'), ('film_score', 'Film Score')], default='classical', max_length=50),
        ),
    ]
